#
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# BCM56990 S board PC_PM_CORE configuration.
#
---
device:
    0:
        PC_PM_CORE:
            ?
                PC_PM_ID: 22
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x60753412
                TX_LANE_MAP: 0x76543210
                RX_POLARITY_FLIP: 0xac
                TX_POLARITY_FLIP: 0x00
            ?
                PC_PM_ID: 25
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x62153047
                TX_LANE_MAP: 0x76543210
                RX_POLARITY_FLIP: 0xaa
                TX_POLARITY_FLIP: 0x00
            ?
                PC_PM_ID: 28
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x73154026
                TX_LANE_MAP: 0x76540123
                RX_POLARITY_FLIP: 0x0f
                TX_POLARITY_FLIP: 0x0f
            ?
                PC_PM_ID: 30
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x26045713
                TX_LANE_MAP: 0x10326475
                RX_POLARITY_FLIP: 0x8d
                TX_POLARITY_FLIP: 0x01
            ?
                PC_PM_ID: 35
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x51732064
                TX_LANE_MAP: 0x64751032
                RX_POLARITY_FLIP: 0x72
                TX_POLARITY_FLIP: 0x50
            ?
                PC_PM_ID: 37
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x40265317
                TX_LANE_MAP: 0x23015476
                RX_POLARITY_FLIP: 0xf0
                TX_POLARITY_FLIP: 0x0f
            ?
                PC_PM_ID: 40
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x40265137
                TX_LANE_MAP: 0x23016745
                RX_POLARITY_FLIP: 0xf0
                TX_POLARITY_FLIP: 0x00
            ?
                PC_PM_ID: 43
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x40265317
                TX_LANE_MAP: 0x23016745
                RX_POLARITY_FLIP: 0x74
                TX_POLARITY_FLIP: 0x00
            ?
                PC_PM_ID: 65
                CORE_INDEX: 0
            :
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_POLARITY_FLIP: 0xf
                TX_POLARITY_FLIP: 0x3
