#
# BCM56883 20x400g port configuration.
#
# configuration yaml file
#   device:
#       <unit>:
#           <table>:
#               ?
#                   <key_fld_1>: <value>
#                   <key_fld_2>: <value>
#                   ...
#                   <key_fld_n>: <value>
#               :
#                   <data_fld_1>: <value>
#                   <data_fld_2>: <value>
#                   ...
#                   <data_fld_n>: <value>
#

---
device:
    0:
        DEVICE_CONFIG:
            # CORE CLOCK FREQUENCY
            CORE_CLK_FREQ: CLK_1350MHZ
            # PP CLOCK FREQUENCY
            PP_CLK_FREQ: CLK_950MHZ
...
---
device:
    0:
        PC_PM_CORE:
            ?
                PC_PM_ID: 1
                CORE_INDEX: 0
            :
                RX_LANE_MAP: 0x03652147
                TX_LANE_MAP: 0x47216503
                RX_POLARITY_FLIP: 0x55
                TX_POLARITY_FLIP: 0x00
            ?
                PC_PM_ID: 2
                CORE_INDEX: 0
            :
                RX_LANE_MAP: 0x47152036
                TX_LANE_MAP: 0x21450367
                RX_POLARITY_FLIP: 0x7c
                TX_POLARITY_FLIP: 0x65
            ?
                PC_PM_ID: 4
                CORE_INDEX: 0
            :
                RX_LANE_MAP: 0x76105432
                TX_LANE_MAP: 0x01673245
                RX_POLARITY_FLIP: 0x65
                TX_POLARITY_FLIP: 0x30
            ?
                PC_PM_ID: 6
                CORE_INDEX: 0
            :
                RX_LANE_MAP: 0x76105432
                TX_LANE_MAP: 0x67014532
                RX_POLARITY_FLIP: 0x30
                TX_POLARITY_FLIP: 0x3f
            ?
                PC_PM_ID: 8
                CORE_INDEX: 0
            :
                RX_LANE_MAP: 0x67014523
                TX_LANE_MAP: 0x01673245
                RX_POLARITY_FLIP: 0x9a
                TX_POLARITY_FLIP: 0x30
            ?
                PC_PM_ID: 9
                CORE_INDEX: 0
            :
                RX_LANE_MAP: 0x10753264
                TX_LANE_MAP: 0x10673254
                RX_POLARITY_FLIP: 0x3f
                TX_POLARITY_FLIP: 0xcf
            ?
                PC_PM_ID: 11
                CORE_INDEX: 0
            :
                RX_LANE_MAP: 0x01572346
                TX_LANE_MAP: 0x67105432
                RX_POLARITY_FLIP: 0x95
                TX_POLARITY_FLIP: 0xc0
            ?
                PC_PM_ID: 13
                CORE_INDEX: 0
            :
                RX_LANE_MAP: 0x01572346
                TX_LANE_MAP: 0x10673254
                RX_POLARITY_FLIP: 0xc0
                TX_POLARITY_FLIP: 0xcf
            ?
                PC_PM_ID: 15
                CORE_INDEX: 0
            :
                RX_LANE_MAP: 0x76420531
                TX_LANE_MAP: 0x46015723
                RX_POLARITY_FLIP: 0xff
                TX_POLARITY_FLIP: 0x60
            ?
                PC_PM_ID: 16
                CORE_INDEX: 0
            :
                RX_LANE_MAP: 0x67014523
                TX_LANE_MAP: 0x67014523
                RX_POLARITY_FLIP: 0x00
                TX_POLARITY_FLIP: 0x00
            ?
                PC_PM_ID: 17
                CORE_INDEX: 0
            :
                RX_LANE_MAP: 0x01672345
                TX_LANE_MAP: 0x67014523
                RX_POLARITY_FLIP: 0xaa
                TX_POLARITY_FLIP: 0x00
            ?
                PC_PM_ID: 18
                CORE_INDEX: 0
            :
                RX_LANE_MAP: 0x42763105
                TX_LANE_MAP: 0x46015723
                RX_POLARITY_FLIP: 0x55
                TX_POLARITY_FLIP: 0x64
            ?
                PC_PM_ID: 20
                CORE_INDEX: 0
            :
                RX_LANE_MAP: 0x57014623
                TX_LANE_MAP: 0x10673254
                RX_POLARITY_FLIP: 0x9a
                TX_POLARITY_FLIP: 0xcf
            ?
                PC_PM_ID: 22
                CORE_INDEX: 0
            :
                RX_LANE_MAP: 0x57014623
                TX_LANE_MAP: 0x67105432
                RX_POLARITY_FLIP: 0xcf
                TX_POLARITY_FLIP: 0xc0
            ?
                PC_PM_ID: 24
                CORE_INDEX: 0
            :
                RX_LANE_MAP: 0x75106432
                TX_LANE_MAP: 0x10673254
                RX_POLARITY_FLIP: 0x65
                TX_POLARITY_FLIP: 0xcf
            ?
                PC_PM_ID: 25
                CORE_INDEX: 0
            :
                RX_LANE_MAP: 0x01672345
                TX_LANE_MAP: 0x01673245
                RX_POLARITY_FLIP: 0xc0
                TX_POLARITY_FLIP: 0x30
            ?
                PC_PM_ID: 27
                CORE_INDEX: 0
            :
                RX_LANE_MAP: 0x10763254
                TX_LANE_MAP: 0x67014532
                RX_POLARITY_FLIP: 0x6a
                TX_POLARITY_FLIP: 0x3f
            ?
                PC_PM_ID: 29
                CORE_INDEX: 0
            :
                RX_LANE_MAP: 0x10763254
                TX_LANE_MAP: 0x01673245
                RX_POLARITY_FLIP: 0x3f
                TX_POLARITY_FLIP: 0x30
            ?
                PC_PM_ID: 31
                CORE_INDEX: 0
            :
                RX_LANE_MAP: 0x15473620
                TX_LANE_MAP: 0x45216703
                RX_POLARITY_FLIP: 0x0c
                TX_POLARITY_FLIP: 0x6a
            ?
                PC_PM_ID: 32
                CORE_INDEX: 0
            :
                RX_LANE_MAP: 0x65034721
                TX_LANE_MAP: 0x21470365
                RX_POLARITY_FLIP: 0xaa
                TX_POLARITY_FLIP: 0xff
...
---
device:
    0:
        PC_PORT_PHYS_MAP:
            ?
                # CPU port
                PORT_ID: 0
            :
                PC_PHYS_PORT_ID: 0
            ?
                PORT_ID: 1
            :
                PC_PHYS_PORT_ID: 1
            ?
                PORT_ID: 2
            :
                PC_PHYS_PORT_ID: 9
            ?
                PORT_ID: 4
            :
                PC_PHYS_PORT_ID: 25
            ?
                PORT_ID: 21
            :
                PC_PHYS_PORT_ID: 41
            ?
                PORT_ID: 23
            :
                PC_PHYS_PORT_ID: 57
            ?
                PORT_ID: 40
            :
                PC_PHYS_PORT_ID: 65
            ?
                PORT_ID: 42
            :
                PC_PHYS_PORT_ID: 81
            ?
                PORT_ID: 60
            :
                PC_PHYS_PORT_ID: 97
            ?
                PORT_ID: 62
            :
                PC_PHYS_PORT_ID: 113
            ?
                PORT_ID: 63
            :
                PC_PHYS_PORT_ID: 121
            ?
                PORT_ID: 80
            :
                PC_PHYS_PORT_ID: 129
            ?
                PORT_ID: 81
            :
                PC_PHYS_PORT_ID: 137
            ?
                PORT_ID: 83
            :
                PC_PHYS_PORT_ID: 153
            ?
                PORT_ID: 101
            :
                PC_PHYS_PORT_ID: 169
            ?
                PORT_ID: 103
            :
                PC_PHYS_PORT_ID: 185
            ?
                PORT_ID: 120
            :
                PC_PHYS_PORT_ID: 193
            ?
                PORT_ID: 122
            :
                PC_PHYS_PORT_ID: 209
            ?
                PORT_ID: 140
            :
                PC_PHYS_PORT_ID: 225
            ?
                PORT_ID: 142
            :
                PC_PHYS_PORT_ID: 241
            ?
                PORT_ID: 143
            :
                PC_PHYS_PORT_ID: 249
            ?
                # Management port 0 (Pipe 1)
                PORT_ID: 38
            :
                PC_PHYS_PORT_ID: 257
            ?
                # Management port 3 (Pipe 7)
                PORT_ID: 158
            :
                PC_PHYS_PORT_ID: 260
...
---
device:
    0:
        PC_PORT:
            ?
                PORT_ID: 0
            :
                &port_mode_10g
                ENABLE: 1
                SPEED: 10000
                NUM_LANES: 1
            ?
                PORT_ID: [1, 2, 4,
                          21, 23,
                          40, 42,
                          60, 62, 63,
                          80, 81, 83,
                          101, 103,
                          120, 122,
                          140, 142, 143]
            :
                &port_mode_400g
                ENABLE: 1
                SPEED: 400000
                NUM_LANES: 8
                FEC_MODE: PC_FEC_RS544_2XN
                MAX_FRAME_SIZE: 0x3fe8
            ?
                PORT_ID: [38,     # Management port 0 (Pipe 1)
                          158]    # Management port 3 (Pipe 7)
            :
                &port_mode_10g_xfi
                ENABLE: 1
                SPEED: 10000
                NUM_LANES: 1
                MAX_FRAME_SIZE: 0x3fe8
...
---
device:
    0:
        TM_SCHEDULER_CONFIG:
            NUM_MC_Q: NUM_MC_Q_4
...
