#
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# BCM56880 PC_PM_CORE configuration for S board.
#
---
device:
    0:
        PC_PM_CORE:
            ?
                PC_PM_ID: 8
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x04152736
                TX_LANE_MAP: 0x40526173
                RX_POLARITY_FLIP: 0x00
                TX_POLARITY_FLIP: 0x89
            ?
                PC_PM_ID: 10
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x01674352
                TX_LANE_MAP: 0x13027654
                RX_POLARITY_FLIP: 0xff
                TX_POLARITY_FLIP: 0xfa
            ?
                PC_PM_ID: 12
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x46570312
                TX_LANE_MAP: 0x72530614
                RX_POLARITY_FLIP: 0xff
                TX_POLARITY_FLIP: 0xe8
            ?
                PC_PM_ID: 14
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x27360514
                TX_LANE_MAP: 0x20314567
                RX_POLARITY_FLIP: 0xab
                TX_POLARITY_FLIP: 0xf7
            ?
                PC_PM_ID: 19
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x05143726
                TX_LANE_MAP: 0x20317456
                RX_POLARITY_FLIP: 0x05
                TX_POLARITY_FLIP: 0xab
            ?
                PC_PM_ID: 21
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x46021753
                TX_LANE_MAP: 0x73210654
                RX_POLARITY_FLIP: 0xcc
                TX_POLARITY_FLIP: 0xeb
            ?
                PC_PM_ID: 23
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x14506723
                TX_LANE_MAP: 0x03152674
                RX_POLARITY_FLIP: 0x8c
                TX_POLARITY_FLIP: 0x0f
            ?
                PC_PM_ID: 25
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x25613074
                TX_LANE_MAP: 0x72405163
                RX_POLARITY_FLIP: 0x37
                TX_POLARITY_FLIP: 0xac
            ?
                PC_PM_ID: 33
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x3012
                TX_LANE_MAP: 0x2031
                RX_POLARITY_FLIP: 0x0d
                TX_POLARITY_FLIP: 0x02
...
