#
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# BCM56992 device configuration.
#

---
device:
    0:
        DEVICE_CONFIG:
            CORE_CLK_FREQ: CLK_1125MHZ
            PP_CLK_FREQ: CLK_675MHZ
...
