#
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# BCM56880 PC_PM_CORE configuration for K board.
#
# $Copyright:.$
#

---
device:
    0:
        PC_PM_CORE:
            ?
                PC_PM_ID: 1
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x40615372
                TX_LANE_MAP: 0x67315204
                RX_POLARITY_FLIP: 0x55
                TX_POLARITY_FLIP: 0xfd
            ?
                PC_PM_ID: 2
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x67241053
                TX_LANE_MAP: 0x04715362
                RX_POLARITY_FLIP: 0xe8
                TX_POLARITY_FLIP: 0x35
            ?
                PC_PM_ID: 3
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x23451706
                TX_LANE_MAP: 0x30571246
                RX_POLARITY_FLIP: 0xff
                TX_POLARITY_FLIP: 0x47
            ?
                PC_PM_ID: 4
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x46532071
                TX_LANE_MAP: 0x67210435
                RX_POLARITY_FLIP: 0xff
                TX_POLARITY_FLIP: 0xaf
            ?
                PC_PM_ID: 5
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x47025631
                TX_LANE_MAP: 0x02641375
                RX_POLARITY_FLIP: 0x55
                TX_POLARITY_FLIP: 0x0b
            ?
                PC_PM_ID: 6
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x40675123
                TX_LANE_MAP: 0x64037512
                RX_POLARITY_FLIP: 0x9a
                TX_POLARITY_FLIP: 0x15
            ?
                PC_PM_ID: 7
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x47035621
                TX_LANE_MAP: 0x12760354
                RX_POLARITY_FLIP: 0x55
                TX_POLARITY_FLIP: 0x82
            ?
                PC_PM_ID: 8
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x02573146
                TX_LANE_MAP: 0x75126403
                RX_POLARITY_FLIP: 0xaa
                TX_POLARITY_FLIP: 0x4c
            ?
                PC_PM_ID: 9
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x03471265
                TX_LANE_MAP: 0x65017423
                RX_POLARITY_FLIP: 0xaa
                TX_POLARITY_FLIP: 0xed
            ?
                PC_PM_ID: 10
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x57034612
                TX_LANE_MAP: 0x03741265
                RX_POLARITY_FLIP: 0x55
                TX_POLARITY_FLIP: 0xe8
            ?
                PC_PM_ID: 11
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x03471265
                TX_LANE_MAP: 0x65017423
                RX_POLARITY_FLIP: 0xaa
                TX_POLARITY_FLIP: 0xed
            ?
                PC_PM_ID: 12
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x67402351
                TX_LANE_MAP: 0x03741265
                RX_POLARITY_FLIP: 0x95
                TX_POLARITY_FLIP: 0xe8
            ?
                PC_PM_ID: 13
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x10675423
                TX_LANE_MAP: 0x53216704
                RX_POLARITY_FLIP: 0xaa
                TX_POLARITY_FLIP: 0xe3
            ?
                PC_PM_ID: 14
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x35062417
                TX_LANE_MAP: 0x03471256
                RX_POLARITY_FLIP: 0x00
                TX_POLARITY_FLIP: 0x01
            ?
                PC_PM_ID: 15
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x21453076
                TX_LANE_MAP: 0x60125743
                RX_POLARITY_FLIP: 0xff
                TX_POLARITY_FLIP: 0xbb
            ?
                PC_PM_ID: 16
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x21573046
                TX_LANE_MAP: 0x67135204
                RX_POLARITY_FLIP: 0xaa
                TX_POLARITY_FLIP: 0xfc
            ?
                PC_PM_ID: 17
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x12573046
                TX_LANE_MAP: 0x46017523
                RX_POLARITY_FLIP: 0xaa
                TX_POLARITY_FLIP: 0xdb
            ?
                PC_PM_ID: 18
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x21563047
                TX_LANE_MAP: 0x57306412
                RX_POLARITY_FLIP: 0xff
                TX_POLARITY_FLIP: 0x4f
            ?
                PC_PM_ID: 19
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x53102467
                TX_LANE_MAP: 0x02571364
                RX_POLARITY_FLIP: 0x21
                TX_POLARITY_FLIP: 0x2c
            ?
                PC_PM_ID: 20
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x10675423
                TX_LANE_MAP: 0x27056413
                RX_POLARITY_FLIP: 0xaa
                TX_POLARITY_FLIP: 0xfa
            ?
                PC_PM_ID: 21
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x67402351
                TX_LANE_MAP: 0x20761453
                RX_POLARITY_FLIP: 0x95
                TX_POLARITY_FLIP: 0x98
            ?
                PC_PM_ID: 22
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x03572146
                TX_LANE_MAP: 0x76205314
                RX_POLARITY_FLIP: 0xaa
                TX_POLARITY_FLIP: 0x99
            ?
                PC_PM_ID: 23
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x57034612
                TX_LANE_MAP: 0x20751463
                RX_POLARITY_FLIP: 0x55
                TX_POLARITY_FLIP: 0x98
            ?
                PC_PM_ID: 24
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x03572146
                TX_LANE_MAP: 0x76205314
                RX_POLARITY_FLIP: 0xaa
                TX_POLARITY_FLIP: 0x99
            ?
                PC_PM_ID: 25
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x21573046
                TX_LANE_MAP: 0x57026413
                RX_POLARITY_FLIP: 0xaa
                TX_POLARITY_FLIP: 0x6d
            ?
                PC_PM_ID: 26
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x47136502
                TX_LANE_MAP: 0x01572463
                RX_POLARITY_FLIP: 0x55
                TX_POLARITY_FLIP: 0x24
            ?
                PC_PM_ID: 27
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x40675123
                TX_LANE_MAP: 0x57026314
                RX_POLARITY_FLIP: 0x9a
                TX_POLARITY_FLIP: 0x7f
            ?
                PC_PM_ID: 28
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x47136502
                TX_LANE_MAP: 0x02761453
                RX_POLARITY_FLIP: 0x55
                TX_POLARITY_FLIP: 0x7e
            ?
                PC_PM_ID: 29
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x54126073
                TX_LANE_MAP: 0x65124703
                RX_POLARITY_FLIP: 0xff
                TX_POLARITY_FLIP: 0x5f
            ?
                PC_PM_ID: 30
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x73062415
                TX_LANE_MAP: 0x01472365
                RX_POLARITY_FLIP: 0xff
                TX_POLARITY_FLIP: 0x00
            ?
                PC_PM_ID: 31
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x21643075
                TX_LANE_MAP: 0x17520436
                RX_POLARITY_FLIP: 0xff
                TX_POLARITY_FLIP: 0xa9
            ?
                PC_PM_ID: 32
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x40735162
                TX_LANE_MAP: 0x57130624
                RX_POLARITY_FLIP: 0xff
                TX_POLARITY_FLIP: 0x28
...
