#
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# BCM56880 BCM device configuration.
#
# configuration yaml file
#
# bcm_device:
#     <unit>:
#         global:
#             <property_1>: <value>
#             <property_2>: <value>
#         port:
#             <key>:
#                 <property_1>: <value>
#                 <property_2>: <value>
#
# $Copyright:.$
#

---
bcm_device:
    0:
        global:
            bcm_tunnel_term_compatible_mode: 0
            vlan_auto_stack: 0
            l3_disable_add_to_arl: 0
            l3_enable: 1
            vlan_default_port: 0
            l2age_thread_pri: 50
            cb_abort_on_err: 0
            l2_learn_enable: 1
            qos_l2_size: 512
            qos_l3_size: 1024
            qos_mpls_size: 512
            flowtracker_elephant_expected_queue_drain_time_usecs: 100
            sram_scan_chunk_size: 256
            sram_scan_enable: 1
            sram_scan_rate: 4096
            sram_scan_interval: 100000
            failover_fixed_nh_offset_enable: 0
            l3_alpm2_default_route_data_mode: 1
            fpem_mem_entries: 0
            ftem_mem_entries: 0
            ip4_mc_group_table_entries_max: -1
            ip6_mc_group_table_entries_max: -1
            ip4_l2mc_table_entries_max: -1
            ip6_l2mc_table_entries_max: -1
            ip4_mc_source_group_table_entries_max: -1
            ip6_mc_source_group_table_entries_max: -1
            ip4_uc_table_entries_max: -1
            ip6_uc_table_entries_max: -1
            multi_hash_recurse_depth_l2: -1
            multi_hash_recurse_depth_l3: -1
            multi_hash_recurse_depth_exact_match: -1
            multi_hash_recurse_depth_vlan_1: -1
            multi_hash_recurse_depth_vlan_2: -1
            multi_hash_recurse_depth_egress_vlan_1: -1
            multi_hash_recurse_depth_egress_vlan_2: -1
            multi_hash_recurse_depth_l3_tunnel: -1
            multi_hash_recurse_depth_vlan_3: -1
            multi_hash_recurse_depth_l2_tunnel: -1
            multi_hash_recurse_depth_l2_tunnel_vnid: -1
            multi_hash_recurse_depth_flow_tracker: -1
            multi_hash_recurse_depth_ipmc_group: -1
            multi_hash_recurse_depth_ipmc_source_group: -1
            multi_hash_recurse_depth_l2mc: -1
            max_vp_lags: 0
            l3_alpm_template: 1
            ipv6_lpm_128b_enable: 1
            telemetry_export_max_packet_size: 1500
            telemetry_max_ports_monitor: 0
            pktio_mode: 0
            uft_mode: 3
            flowtracker_enable: 0
            flowtracker_max_flow_groups: 255
            flowtracker_enterprise_number: 0
            flowtracker_max_export_pkt_length: 1500
            flowtracker_flow_start_timestamp_ie_enable: 0
            flowtracker_elephant_enable: 0
            flowtracker_hostmem_enable: 0
            flowtracker_scan_interval_usecs: 500000
            flowtracker_hardware_learn_enable: 0
            skip_port_hw_init: 0
            l2_hitbit_enable: 0
            vlan_flooding_l2mc_num_reserved: 2048
...
---
bcm_device:
    0:
        port:
            "*":
                encap_mode: IEEE
...
